language: python

#which versions of python to test against
python:
  - "3.6"

# command to install dependencies
install:
    - pip install codecov
    - pip install coverage
#  - pip install -r ./lecture7/requirements.txt

script: 
  - python -m unittest discover -v ./q1/ # command to run unit tes
  - coverage run ./q1/tests.py

#can do additional things, say send out reports, which we will discuss next time 
after_success:
    - codecov --token=aae7786d-9294-4ad9-8624-c8a2f188867c
